url: https://labs.controlsoft.com.br
baseurl: /

# Site settings
title: ControlSoft Labs
email: patrick@controlsoft.com.br
description: "Site da ControlSoft para divulgação de conteúdos e projetos de código aberto"


# Team names, titles and social links
people:
- name: Amanda
  pic: deva
  position: Qualidade
  social:
    - title: stack-overflow
      url: #

- name: Anderson
  pic: anderson_campos
  position: Desenvolvedor
  social:
    - title: github
      url: https://github.com/AndersondaCampo

- name: Athauã
  pic: athaua_machado
  position: Desenvolvedor
  social:
    - title: github
      url: https://github.com/Athaua

- name: Carine
  pic: deva
  position: Qualidade
  social:
    - title: stack-overflow
      url: #

- name: Charles
  pic: dev
  position: Qualidade
  social:
    - title: stack-overflow
      url: #

- name: Érica
  pic: erica_jadoski
  position: Desenvolvedora
  social:
    - title: github
      url: https://github.com/ErikaPaulaJadoski

- name: Everson
  pic: everson_turrosi
  position: Desenvolvedor
  social:
    - title: github
      url: https://github.com/eversonturossi

- name: Fabio
  pic: fabio_alecsandro
  position: Desenvolvedor
  social:
    - title: github
      url: https://github.com/FabioAlec

- name: Lucinei
  pic: lucinei_loch
  position: Desenvolvedor
  social:
    - title: github
      url: https://github.com/agrimindapps

- name: Magno
  pic: magno_ritzman
  position: Desenvolvedor
  social:
    - title: github
      url: https://github.com/magnoritzmann

- name: Patrick
  pic: patrick_kamiski
  position: Desenvolvedor
  social:
    - title: github
      url: https://github.com/patrix

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/controlsoftagro
  - title: facebook
    url: https://pt-br.facebook.com/ControlSoft
  - title: instagram
    url: https://www.instagram.com/controlsoft/?hl=pt
  - title: github
    url: https://github.com/ControlSoft-Labs

# Postal address (add as many lines as necessary)
address:
  - line: Av. Natalino João Brescasin, 2753 
  - line: Centro, Sorriso - MT, 78890-000

# Build settings
markdown: kramdown
permalink: pretty