url: https://labs.controlsoft.com.br
baseurl: /

# Site settings
title: ControlSoft Labs
email: patrick@controlsoft.com.br
description: "Site da ControlSoft para divulgação de conteúdos e projetos de código aberto"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/controlsoftagro
  - title: facebook
    url: https://pt-br.facebook.com/ControlSoft
  - title: instagram
    url: https://www.instagram.com/controlsoft/?hl=pt
  - title: github
    url: https://github.com/ControlSoft-Labs

# Postal address (add as many lines as necessary)
address:
  - line: Av. Natalino João Brescasin, 2753 
  - line: Centro, Sorriso - MT, 78890-000

# Build settings
markdown: kramdown
permalink: pretty